#!/usr/bin/env bash
# Put the `dario` command on PATH.
#
#   scripts/install-bin.sh              install a self-contained snapshot
#   scripts/install-bin.sh --link       run the checkout live instead
#   scripts/install-bin.sh --uninstall  remove it
#
# User scope, no sudo: the launcher goes in ~/.local/bin, which is already
# on PATH on most distributions and is the right place for a per-user
# command. Override with DARIO_BIN_DIR / DARIO_LIB_DIR.
#
# Default is a SNAPSHOT: dist/ and package.json are copied into
# ~/.local/lib/dario and the launcher runs that copy. Build output often
# lives somewhere other than the checkout — dist/ is commonly a symlink to
# a scratch or external volume — and a launcher that execs through it dies
# the moment that volume goes away:
#
#   dario: /path/to/checkout/dist/cli.js is missing — the checkout moved
#
# Copying is cheap (dario has zero runtime dependencies and dist/ is a
# couple of megabytes), so the installed command depends on nothing but
# $HOME and bun. Build wherever you like; the thing on PATH stays put.
#
# --link keeps the old behaviour — exec the checkout directly, so a
# rebuild is picked up with no reinstall. Right for active development,
# wrong for anything on removable storage.
#
# A generated wrapper rather than a symlink to dist/cli.js either way. The
# entry point is `#!/usr/bin/env bun`, so a symlink on a host without bun
# on PATH dies with `env: 'bun': No such file or directory` and exit 127 —
# before any of dario's own code runs, which means the friendly "install
# Bun" message never gets the chance to print. The wrapper pins the
# absolute bun path it found at install time and re-checks at run time, so
# the failure explains itself. Same reasoning as the systemd unit's
# absolute ExecStart.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${DARIO_BIN_DIR:-$HOME/.local/bin}"
BIN_PATH="$BIN_DIR/dario"
LIB_DIR="${DARIO_LIB_DIR:-$HOME/.local/lib/dario}"
MARKER="# generated by dario scripts/install-bin.sh"

die() { printf '\033[31merror\033[0m %s\n' "$*" >&2; exit 1; }
info() { printf '\033[36m→\033[0m %s\n' "$*"; }
ok() { printf '\033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*" >&2; }

# Single-quote a value for safe interpolation into the generated wrapper.
# The repo path is attacker-free but not shell-free: a checkout under
# ~/my projects or ~/it's mine has to survive verbatim.
shq() { printf "'%s'" "${1//\'/\'\\\'\'}"; }

# Only ever remove a file this script wrote. Anything else at that path
# belongs to the user (or to npm), and silently replacing it is how a
# package manager's copy disappears.
is_ours() { [ -f "$1" ] && grep -qF "$MARKER" "$1" 2>/dev/null; }

uninstall() {
  if [ ! -e "$BIN_PATH" ]; then
    info "No launcher at $BIN_PATH"
  elif is_ours "$BIN_PATH"; then
    rm -f "$BIN_PATH"
    ok "Removed $BIN_PATH"
  else
    die "$BIN_PATH exists but was not written by this script — leaving it alone."
  fi
  # Only ever remove a lib dir carrying our marker, for the same reason.
  if [ -f "$LIB_DIR/.dario-source" ]; then
    rm -rf "$LIB_DIR"
    ok "Removed $LIB_DIR"
  fi
  ok "dario command removed."
}

# Copy the built output somewhere that does not depend on the checkout.
# `cp -RL` dereferences: dist/ is frequently a symlink to a build volume,
# and copying the link instead of its contents would defeat the point.
# package.json rides along because dist/cli.js resolves `../package.json`
# for its own version, so the snapshot has to reproduce that layout.
snapshot() {
  local entry="$1"
  local src_dist
  src_dist="$(cd "$(dirname "$entry")" && pwd)"

  rm -rf "$LIB_DIR"
  mkdir -p "$LIB_DIR"
  cp -RL "$src_dist" "$LIB_DIR/dist"
  cp -L "$REPO_ROOT/package.json" "$LIB_DIR/package.json"
  printf '%s\n' "$REPO_ROOT" > "$LIB_DIR/.dario-source"

  # A snapshot that still points at the volume it was copied from is not a
  # snapshot. Cheap to verify, and the failure is otherwise invisible until
  # the drive is unplugged.
  if find "$LIB_DIR" -type l | grep -q .; then
    warn "The snapshot contains symlinks; it may still depend on the build volume:"
    find "$LIB_DIR" -type l | head -5 >&2
  fi
  echo "$LIB_DIR/dist/cli.js"
}

install_bin() {
  local mode="${1:-snapshot}"
  local bun_bin
  bun_bin="$(command -v bun || true)"
  [ -n "$bun_bin" ] || die "bun not found on PATH. Install from https://bun.sh and retry."
  bun_bin="$(cd "$(dirname "$bun_bin")" && pwd)/$(basename "$bun_bin")"

  # Same floor as the systemd installer and package.json engines: Bun is
  # the runtime, not an optimisation — the TLS fingerprint and fetch's
  # proxy option both depend on it.
  local bun_ver min="1.4.0"
  bun_ver="$("$bun_bin" --version 2>/dev/null | tr -d '\n')"
  if [ "$(printf '%s\n%s\n' "$min" "$bun_ver" | sort -V | head -n1)" != "$min" ]; then
    die "bun $bun_ver is older than the required $min. Upgrade with: bun upgrade"
  fi

  local entry="$REPO_ROOT/dist/cli.js"
  if [ ! -f "$entry" ]; then
    info "Building $REPO_ROOT"
    cd "$REPO_ROOT" || die "cannot enter $REPO_ROOT"
    bun install --frozen-lockfile >/dev/null 2>&1 || bun install >/dev/null
    bun run build >/dev/null
    cd - >/dev/null || true
  fi
  [ -f "$entry" ] || die "build did not produce $entry"

  # Resolve to what the launcher will actually exec.
  local run_entry desc
  if [ "$mode" = "link" ]; then
    run_entry="$entry"
    desc="the checkout (live — a rebuild is picked up with no reinstall)"
  else
    info "Copying the build into $LIB_DIR"
    run_entry="$(snapshot "$entry")"
    desc="a snapshot (independent of $REPO_ROOT and wherever it builds to)"
  fi

  mkdir -p "$BIN_DIR"

  if [ -e "$BIN_PATH" ] && ! is_ours "$BIN_PATH"; then
    die "$BIN_PATH already exists and was not written by this script.
  It is probably an npm or bun global install. Remove it first, or set
  DARIO_BIN_DIR to install this checkout somewhere else on PATH."
  fi

  cat > "$BIN_PATH" <<EOF
#!/usr/bin/env bash
$MARKER
# Installed from $REPO_ROOT — re-run that script to refresh.
set -euo pipefail
BUN=$(shq "$bun_bin")
[ -x "\$BUN" ] || BUN="\$(command -v bun || true)"
if [ -z "\$BUN" ] || [ ! -x "\$BUN" ]; then
  echo "dario: bun is not installed or no longer at $bun_bin" >&2
  echo "dario needs the Bun runtime — its TLS fingerprint and proxy support depend on it." >&2
  echo "Install from https://bun.sh, then re-run $REPO_ROOT/scripts/install-bin.sh" >&2
  exit 127
fi
ENTRY=$(shq "$run_entry")
if [ ! -f "\$ENTRY" ]; then
  echo "dario: \$ENTRY is missing." >&2
  echo "Reinstall with: cd $REPO_ROOT && bun run build && scripts/install-bin.sh" >&2
  exit 127
fi
exec "\$BUN" "\$ENTRY" "\$@"
EOF
  chmod 755 "$BIN_PATH"
  ok "Wrote $BIN_PATH → $run_entry"
  info "Runs $desc"

  # Shadowing is the failure people actually hit: an npm-global dario
  # earlier on PATH means `dario` keeps running the old copy and every
  # change here looks like it did nothing.
  local first
  first="$(command -v dario 2>/dev/null || true)"
  if [ -n "$first" ] && [ "$first" != "$BIN_PATH" ]; then
    warn "Another dario is earlier on PATH and wins: $first"
    warn "Remove it, or put $BIN_DIR ahead of it in PATH."
  fi

  case ":${PATH}:" in
    *":$BIN_DIR:"*)
      ok "$BIN_DIR is on PATH."
      ;;
    *)
      warn "$BIN_DIR is not on PATH. Add it:"
      # SC2016: $PATH must stay literal — this is a line for the user to
      # paste into their shell rc, not one for us to expand.
      # shellcheck disable=SC2016
      case "$(basename "${SHELL:-}")" in
        zsh)  printf '\n    echo '\''export PATH="%s:$PATH"'\'' >> ~/.zshrc && exec zsh\n\n' "$BIN_DIR" ;;
        bash) printf '\n    echo '\''export PATH="%s:$PATH"'\'' >> ~/.bashrc && exec bash\n\n' "$BIN_DIR" ;;
        fish) printf '\n    fish_add_path %s\n\n' "$BIN_DIR" ;;
        *)    printf '\n    export PATH="%s:$PATH"\n\n' "$BIN_DIR" ;;
      esac
      ;;
  esac

  cat <<EOF

  dario --version      confirm the launcher works
  dario                the TUI
  dario proxy          run the proxy in the foreground
  dario doctor         health report
EOF
  if [ "$mode" = "link" ]; then
    cat <<EOF

  Runs $REPO_ROOT live — a \`git pull\` + \`bun run build\` is picked up
  with no reinstall. It breaks if that path (or the volume dist/ builds
  to) goes away; drop --link for a copy that doesn't.
EOF
  else
    cat <<EOF

  Independent of $REPO_ROOT: unplugging the drive it builds to won't
  break the command. After a \`git pull\` + \`bun run build\`, re-run
  \`$REPO_ROOT/scripts/install-bin.sh\` to refresh the copy.
EOF
  fi
}

main() {
  case "${1:-install}" in
    install|"")   install_bin snapshot ;;
    --link)       install_bin link ;;
    --uninstall)  uninstall ;;
    -h|--help)
      sed -n '2,10p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      ;;
    *) die "unknown argument: $1 (expected --link, --uninstall, or no argument)" ;;
  esac
}

main "$@"
