#!/usr/bin/env bash
# Put the `dario` command on PATH, pointing at this checkout.
#
#   scripts/install-bin.sh              install (or refresh) the launcher
#   scripts/install-bin.sh --uninstall  remove it
#
# User scope, no sudo: the launcher goes in ~/.local/bin, which is already
# on PATH on most distributions and is the right place for a per-user
# command. Override with DARIO_BIN_DIR to install somewhere else.
#
# A generated wrapper rather than a symlink to dist/cli.js. The entry point
# is `#!/usr/bin/env bun`, so a symlink on a host without bun on PATH dies
# with `env: 'bun': No such file or directory` and exit 127 — before any of
# dario's own code runs, which means the friendly "install Bun" message
# never gets the chance to print. The wrapper pins the absolute bun path it
# found at install time and re-checks at run time, so the failure explains
# itself. Same reasoning as the systemd unit's absolute ExecStart.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${DARIO_BIN_DIR:-$HOME/.local/bin}"
BIN_PATH="$BIN_DIR/dario"
MARKER="# generated by dario scripts/install-bin.sh"

die() { printf '\033[31merror\033[0m %s\n' "$*" >&2; exit 1; }
info() { printf '\033[36m→\033[0m %s\n' "$*"; }
ok() { printf '\033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*" >&2; }

# Single-quote a value for safe interpolation into the generated wrapper.
# The repo path is attacker-free but not shell-free: a checkout under
# ~/my projects or ~/it's mine has to survive verbatim.
shq() { printf "'%s'" "${1//\'/\'\\\'\'}"; }

# Only ever remove a file this script wrote. Anything else at that path
# belongs to the user (or to npm), and silently replacing it is how a
# package manager's copy disappears.
is_ours() { [ -f "$1" ] && grep -qF "$MARKER" "$1" 2>/dev/null; }

uninstall() {
  if [ ! -e "$BIN_PATH" ]; then
    info "No launcher at $BIN_PATH"
  elif is_ours "$BIN_PATH"; then
    rm -f "$BIN_PATH"
    ok "Removed $BIN_PATH"
  else
    die "$BIN_PATH exists but was not written by this script — leaving it alone."
  fi
  ok "dario command removed."
}

install_bin() {
  local bun_bin
  bun_bin="$(command -v bun || true)"
  [ -n "$bun_bin" ] || die "bun not found on PATH. Install from https://bun.sh and retry."
  bun_bin="$(cd "$(dirname "$bun_bin")" && pwd)/$(basename "$bun_bin")"

  # Same floor as the systemd installer and package.json engines: Bun is
  # the runtime, not an optimisation — the TLS fingerprint and fetch's
  # proxy option both depend on it.
  local bun_ver min="1.4.0"
  bun_ver="$("$bun_bin" --version 2>/dev/null | tr -d '\n')"
  if [ "$(printf '%s\n%s\n' "$min" "$bun_ver" | sort -V | head -n1)" != "$min" ]; then
    die "bun $bun_ver is older than the required $min. Upgrade with: bun upgrade"
  fi

  local entry="$REPO_ROOT/dist/cli.js"
  if [ ! -f "$entry" ]; then
    info "Building $REPO_ROOT"
    cd "$REPO_ROOT" || die "cannot enter $REPO_ROOT"
    bun install --frozen-lockfile >/dev/null 2>&1 || bun install >/dev/null
    bun run build >/dev/null
    cd - >/dev/null || true
  fi
  [ -f "$entry" ] || die "build did not produce $entry"

  mkdir -p "$BIN_DIR"

  if [ -e "$BIN_PATH" ] && ! is_ours "$BIN_PATH"; then
    die "$BIN_PATH already exists and was not written by this script.
  It is probably an npm or bun global install. Remove it first, or set
  DARIO_BIN_DIR to install this checkout somewhere else on PATH."
  fi

  cat > "$BIN_PATH" <<EOF
#!/usr/bin/env bash
$MARKER
# Runs the dario checkout at $REPO_ROOT. Re-run that script to repoint it.
set -euo pipefail
BUN=$(shq "$bun_bin")
[ -x "\$BUN" ] || BUN="\$(command -v bun || true)"
if [ -z "\$BUN" ] || [ ! -x "\$BUN" ]; then
  echo "dario: bun is not installed or no longer at $bun_bin" >&2
  echo "dario needs the Bun runtime — its TLS fingerprint and proxy support depend on it." >&2
  echo "Install from https://bun.sh, then re-run $REPO_ROOT/scripts/install-bin.sh" >&2
  exit 127
fi
ENTRY=$(shq "$entry")
if [ ! -f "\$ENTRY" ]; then
  echo "dario: \$ENTRY is missing — the checkout moved or was cleaned." >&2
  echo "Rebuild with: cd $REPO_ROOT && bun run build" >&2
  exit 127
fi
exec "\$BUN" "\$ENTRY" "\$@"
EOF
  chmod 755 "$BIN_PATH"
  ok "Wrote $BIN_PATH → $entry"

  # Shadowing is the failure people actually hit: an npm-global dario
  # earlier on PATH means `dario` keeps running the old copy and every
  # change here looks like it did nothing.
  local first
  first="$(command -v dario 2>/dev/null || true)"
  if [ -n "$first" ] && [ "$first" != "$BIN_PATH" ]; then
    warn "Another dario is earlier on PATH and wins: $first"
    warn "Remove it, or put $BIN_DIR ahead of it in PATH."
  fi

  case ":${PATH}:" in
    *":$BIN_DIR:"*)
      ok "$BIN_DIR is on PATH."
      ;;
    *)
      warn "$BIN_DIR is not on PATH. Add it:"
      # SC2016: $PATH must stay literal — this is a line for the user to
      # paste into their shell rc, not one for us to expand.
      # shellcheck disable=SC2016
      case "$(basename "${SHELL:-}")" in
        zsh)  printf '\n    echo '\''export PATH="%s:$PATH"'\'' >> ~/.zshrc && exec zsh\n\n' "$BIN_DIR" ;;
        bash) printf '\n    echo '\''export PATH="%s:$PATH"'\'' >> ~/.bashrc && exec bash\n\n' "$BIN_DIR" ;;
        fish) printf '\n    fish_add_path %s\n\n' "$BIN_DIR" ;;
        *)    printf '\n    export PATH="%s:$PATH"\n\n' "$BIN_DIR" ;;
      esac
      ;;
  esac

  cat <<EOF

  dario --version      confirm the launcher works
  dario                the TUI
  dario proxy          run the proxy in the foreground
  dario doctor         health report

  Points at $REPO_ROOT — a \`git pull\` + \`bun run build\` there is
  picked up immediately; no reinstall needed.
EOF
}

main() {
  case "${1:-install}" in
    install|"")   install_bin ;;
    --uninstall)  uninstall ;;
    -h|--help)
      sed -n '2,9p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      ;;
    *) die "unknown argument: $1 (expected --uninstall or no argument)" ;;
  esac
}

main "$@"
